name: customer_app
description: Pakola Waters customer mobile application.
publish_to: none
version: 0.1.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  authentication:
    path: ../../packages/authentication
  core:
    path: ../../packages/core
  design_system:
    path: ../../packages/design_system
  firebase:
    path: ../../packages/firebase
  go_router: ^16.0.0
  models:
    path: ../../packages/models
  provider: ^6.1.5
  repositories:
    path: ../../packages/repositories
  services:
    path: ../../packages/services
  shared_widgets:
    path: ../../packages/shared_widgets

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
