name: services
description: Application services for Pakola Waters.
publish_to: none
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  cloud_firestore: ^5.6.9
  core:
    path: ../core
  firebase:
    path: ../firebase
  firebase_auth: ^5.6.0
  models:
    path: ../models

dev_dependencies:
  flutter_lints: ^6.0.0
