// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDjvndKlPwnN4egPh4a0QSyK5P20TzZlnE',
    appId: '1:534707491606:web:f9355c81d61704f298f637',
    messagingSenderId: '534707491606',
    projectId: 'pakoola-waters',
    authDomain: 'pakoola-waters.firebaseapp.com',
    storageBucket: 'pakoola-waters.firebasestorage.app',
    measurementId: 'G-6863VG4EZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDen09nIAItLjxfxTL4FtJU1nAtMyV-GC0',
    appId: '1:534707491606:android:e2c7ca557ea57dd398f637',
    messagingSenderId: '534707491606',
    projectId: 'pakoola-waters',
    storageBucket: 'pakoola-waters.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6JsrhMYE3REm-zMSXJopzMgimUBqZQxY',
    appId: '1:534707491606:ios:976c9c8561253f1198f637',
    messagingSenderId: '534707491606',
    projectId: 'pakoola-waters',
    storageBucket: 'pakoola-waters.firebasestorage.app',
    iosClientId: '534707491606-mr4nbqquqk044vgvndaomgng8v00ougv.apps.googleusercontent.com',
    iosBundleId: 'com.example.pakolaWaters',
  );
}
